### ISSUE TITLE
Hunk #4 FAILED at 333

### ISSUE THREAD

**Issue by JanGruuthuse** [oscam-emu/oscam-emu#103]
with changeset [10170] to [10173] with simplebuild

apply patch oscam-emu.patch
patching file CMakeLists.txt
patching file config.h
Hunk #1 succeeded at 1 with fuzz 2.
patching file config.sh
Hunk #4 FAILED at 333.
1 out of 5 hunks FAILED -- saving rejects to file config.sh.rej
patching file cscrypt/des.c

**Comment by JanGruuthuse** [comment]
config.sh.rej
=========

--- config.sh	(working copy)
+++ config.sh	(revision 10001)
@@ -331,9 +329,9 @@
 	not_have_flag USE_LIBCRYPTO && echo "CONFIG_LIB_AES=y" || echo "# CONFIG_LIB_AES=n"
 	enabled MODULE_CCCAM && echo "CONFIG_LIB_RC6=y" || echo "# CONFIG_LIB_RC6=n"
 	not_have_flag USE_LIBCRYPTO && enabled MODULE_CCCAM && echo "CONFIG_LIB_SHA1=y" || echo "# CONFIG_LIB_SHA1=n"
-	enabled_any MODULE_NEWCAMD READER_DRE MODULE_SCAM WITH_EMU && echo "CONFIG_LIB_DES=y" || echo "# CONFIG_LIB_DES=n"
-	enabled_any MODULE_CCCAM READER_NAGRA WITH_EMU && echo "CONFIG_LIB_IDEA=y" || echo "# CONFIG_LIB_IDEA=n"
-	not_have_flag USE_LIBCRYPTO && enabled_any READER_CONAX READER_CRYPTOWORKS READER_NAGRA WITH_EMU && echo "CONFIG_LIB_BIGNUM=y" || echo "# CONFIG_LIB_BIGNUM=n"
+	enabled_any MODULE_NEWCAMD READER_DRE MODULE_SCAM && echo "CONFIG_LIB_DES=y" || echo "# CONFIG_LIB_DES=n"
+	enabled_any MODULE_CCCAM READER_NAGRA && echo "CONFIG_LIB_IDEA=y" || echo "# CONFIG_LIB_IDEA=n"
+	not_have_flag USE_LIBCRYPTO && enabled_any READER_CONAX READER_CRYPTOWORKS READER_NAGRA && echo "CONFIG_LIB_BIGNUM=y" || echo "# CONFIG_LIB_BIGNUM=n"
 }
 
 make_config_c() {

**Comment by allemallachen** [comment]
Look at streamboard ... there is a Patch for r10184 ...

**Comment by jahntheman** [comment]
Fixed
