### ISSUE TITLE
r10505 fails to build with patch from 07/02/2015

### ISSUE THREAD

**Issue by JanGruuthuse** [oscam-emu/oscam-emu#127]
module-emulator.c: In function 'add_emu_reader':
module-emulator.c:269:3: error: too many arguments to function 'chk_ftab'
   chk_ftab(ftab, &rdr->ftab, "reader", emuName, "provid");
   ^
In file included from module-emulator.c:10:0:
oscam-conf-chk.h:12:6: note: declared here
 void chk_ftab(char *value, FTAB *ftab);
      ^
make[1]: *** [build/mipsel-openpli40-linux-gnu/module-emulator.o] Error 1
make[1]: *** Waiting for unfinished jobs....
CC	module-ird-guess.c
make: *** [all] Error 2

**Comment by philipphunger** [comment]
Same here...

**Comment by Bigsailor69** [comment]
The same problem and error message when compiling with emu on SH4 processors

**Comment by jahntheman** [comment]
fixed

**Comment by JanGruuthuse** [comment]
thanks
