### ISSUE TITLE
failed against svn10577

### ISSUE THREAD

**Issue by JanGruuthuse** [oscam-emu/oscam-emu#131]
CC	oscam.c
CONF	build/mipsel-openpli40-linux-gnu/config.c
oscam.c: In function 'main':
oscam.c:1539:3: error: 'cardreader_emu' undeclared (first use in this function)
   cardreader_emu,
   ^
oscam.c:1539:3: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [build/mipsel-openpli40-linux-gnu/oscam.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

------
/opt/simplebuild/oscam-svn/csctapi/**cardreaders.h.rej**

--- csctapi/cardreaders.h	(working copy)
+++ csctapi/cardreaders.h	(revision 10569)
@@ -13,6 +13,5 @@
 void cardreader_smartreader(struct s_cardreader *crdr);
 void cardreader_stapi(struct s_cardreader *crdr);
 void cardreader_stinger(struct s_cardreader *crdr);
-void cardreader_emu(struct s_cardreader *crdr);
 
 #endif

**Comment by Bigsailor69** [comment]
This patch (full version of oscam-emu.patch)should fix that error:
http://www.streamboard.tv/wbb2/attachment.php?attachmentid=58139

**Comment by p1ngb4ck** [comment]
the mentioned patch makes my x86_64 version crash instantly on startup ...

**Comment by jahntheman** [comment]
fixed

**Comment by JanGruuthuse** [comment]
thanks: up and running

**Comment by p1ngb4ck** [comment]
<3. just confirming that it compiles without warnings again and runs smoothly =) Thanks !
