### ISSUE TITLE
some compiling issues with latest oscam

### ISSUE THREAD

**Issue by ovidiu31** [oscam-emu/oscam-emu#137]
oscam.c: In function âmainâ:
oscam.c:1539:3: error: âcardreader_emuâ undeclared (first use in this function)
   cardreader_emu,
   ^
oscam.c:1539:3: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [build/x86_64-linux-gnu/oscam.o] Error 1
make: *** [all] Error 2

**Comment by jahntheman** [comment]
updated
