### ISSUE TITLE
Pvu

### ISSUE THREAD

**Issue by nicovil** [oscam-emu/oscam-emu#140]
I checked out this code and noted it has the powervu algorithm implemented on it.

Is there some way to configure pvu keys on softcam.keys?

**Comment by cccamcccc** [comment]
I need to have NDS1 INS54 support

**Comment by nicovil** [comment]
Nds1 ins54 is needed for powervu? Isn't it for videoguard?

**Comment by cccamcccc** [comment]
Yes, he is VideoGuard.
Reader initialization failed
CW encryption.

**Comment by nicovil** [comment]
Buy PowerVU is another encryption different from Videoguard.
Recently colibrí has released a brute force hack paper for PowerVu and it would be nice if oscam-emu supports PowerVU since it is now possible to get the manager keys and then retrieve the ECM keys in real time from processing the EMM, and then decrypt all ECM with the algorithm you implemented on oscam-emu (at least I think this).

**Comment by cccamcccc** [comment]
Hello, my friend, thank you for your words of reply,
PowerVU I know some, but I heard only the C-band can be cracked,
I have here a KU-band, if you can tell me to get back to a receiver test available to you

**Comment by nicovil** [comment]
Hi!

As you said, powerVU is used for C-Band, but here in south america (and seems like north america too) there are some providers which can be retrieved with a 1.2mts dish and a Cband lnb. I have an enigma 2 receiver here and I'm able to retrieve a lot of channels without problem... now I'm looking for some software to brute force the keys (here are a lot of info, but any software was released yet: http://www.satellitetesters.com).

**Comment by cccamcccc** [comment]
hi friends,
I also just learned about this OSCAM EMU,
I think you're great.
I think if you write some simple code I need should be no problem,
I'm looking for people to help me write the code, you have any good suggestions?
Or a good friend? Here it can be attached to email or skype?
Because I came, not just paste them. Ask for your help.
I am always concerned about the KU band PowerVu crack.

**Comment by iptvfta** [comment]
powervu patch can do same like biss to dvb box?  now only openbox team and strong team have added this patch to their box

**Comment by cccamcccc** [comment]
emuOSCAM supports KU band break it?
How I need to do?
Who can teach me.

**Comment by iptvfta** [comment]
i also searching who cna help me add powervu patch to my dvb box like biss softcam function

**Comment by jahntheman** [comment]
pvu has not finished yet.  it is working now,

**Comment by cccamcccc** [comment]
I want to know now was emuOSCAM can be used in X86 server? Share to my partner?

**Comment by iptvfta** [comment]
powervu can working by normal dvb box now?   i still only got info by google , told only startsat, strong and openbox decoder have powervu patch function

**Comment by iptvfta** [comment]
who have powervu source code of NVK78326SE/? i can payment any time. cherrs
