### ISSUE TITLE
OSCam Changeset [10697]  with oscam-emu.patch ea90314

### ISSUE THREAD

**Issue by JanGruuthuse** [oscam-emu/oscam-emu#142]
Hunk #4 FAILED at 4004
...
1 out of 7 hunks FAILED -- saving rejects to file module-webif.c.rej

build.log and module-webif.c.rej 
download: 1.5 kB @ http://www.streamboard.tv/wbb2/attachment.php?attachmentid=59552

**Comment by heugabel** [comment]
i have created a new one. Please be Patient and wait of the admin who can merge the pull request

**Comment by jahntheman** [comment]
fixed

**Comment by JanGruuthuse** [comment]
OSEmu patch up and running on OSCam r10886.
Thanks to all involved.
