### ISSUE TITLE
fail to compile with patch & softcam file

### ISSUE THREAD

**Issue by ovidiu31** [oscam-emu/oscam-emu#143]
root@ubuntu:~/oscam-svn# make
+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 10775 target: x86_64-linux-gnu
| Tools:
|  CROSS    =
|  CC       = gcc
| Settings:
|  CONF_DIR = /usr/local/etc
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   =
|  LDFLAGS  = -Wl,--gc-sections
|  LIBS     = -lpthread -ldl -lrt
|  UseFlags =
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK CLOCKFIX
|  Protocols: CAMD33 CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER
|  Compiler : gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
|  Config   : build/x86_64-linux-gnu/config.mak
|  Binary   : Distribution/oscam-1.20-unstable_svn10775-x86_64-linux-gnu
+-------------------------------------------------------------------------------
CC      module-webif.c
module-webif.c: In function âsend_oscam_filesâ:
module-webif.c:5894:24: error: âMNU_CFG_KEYâ undeclared (first use in this function)
   { "SoftCam.Key",     MNU_CFG_KEY,       FTYPE_CONFIG },
                        ^
module-webif.c:5894:24: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [build/x86_64-linux-gnu/module-webif.o] Error 1
make: *** [all] Error 2

**Comment by jahntheman** [comment]
fixed
