### ISSUE TITLE
File patch doesn't patch in file des.h

### ISSUE THREAD

**Issue by Bigsailor69** [oscam-emu/oscam-emu#146]
When attempting to patch oscam, the file des.h doesn't patch in revision 10875 of oscam. Here the rej file:

--- cscrypt/des.h	(revision 10871)
+++ cscrypt/des.h	(local copy)
@@ -16,6 +16,8 @@
 #define DES_ECS2_CRYPT      (DES_IP | DES_IP_1)
 
 	extern void doPC1(unsigned char data[]);
+	extern void des_ede2_cbc_encrypt(unsigned char *data, const unsigned char *iv, const unsigned char *okey1, const unsigned char *okey2, int len);
+	extern void des_ede2_cbc_decrypt(unsigned char *data, unsigned char *iv, const unsigned char *okey1, const unsigned char *okey2, int len);
 	extern void des(unsigned char key[], unsigned char mode, unsigned char data[]);
 	extern void des_cbc_encrypt(unsigned char *data, const unsigned char *iv, const unsigned char *okey, int len);
 	extern void des_cbc_decrypt(unsigned char *data, unsigned char *iv, const unsigned char *okey, int len);

**Comment by jahntheman** [comment]
fixed
