### ISSUE TITLE
Starting with version 10876, - error

### ISSUE THREAD

**Issue by satxtreme** [oscam-emu/oscam-emu#147]
after oscam-emu.patch not compiled

 CC cscrypt/des.c
cscrypt/des.c:842:6: error: redefinition of 'des_ede2_cbc_encrypt'

    void des_ede2_cbc_encrypt(unsigned char *data, const unsigned char *iv, const unsigned char *okey1, const unsigned char *okey2, int len)

cscrypt/des.c:800:6: note: previous definition of 'des_ede2_cbc_encrypt' was here

    void des_ede2_cbc_encrypt(uint8_t* data, const uint8_t* iv, const uint8_t* key1, const uint8_t* key2, int32_t len)

cscrypt/des.c: In function 'des_ede2_cbc_encrypt':
cscrypt/des.c:850:2: warning: implicit declaration of function 'doPC1' [-Wimplicit-function-declaration]

    doPC1(key1);

cscrypt/des.c:857:12: error: 'DES_ECS2_CRYPT' undeclared (first use in this function)

    des(key1,DES_ECS2_CRYPT,&data[i]);

cscrypt/des.c:857:12: note: each undeclared identifier is reported only once for each function it appears in
cscrypt/des.c:857:27: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key1,DES_ECS2_CRYPT,&data[i]);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

cscrypt/des.c:858:12: error: 'DES_ECS2_DECRYPT' undeclared (first use in this function)

    des(key2,DES_ECS2_DECRYPT,&data[i]);

cscrypt/des.c:858:29: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key2,DES_ECS2_DECRYPT,&data[i]);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

cscrypt/des.c:859:27: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key1,DES_ECS2_CRYPT,&data[i]);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

cscrypt/des.c: At top level:
cscrypt/des.c:863:6: error: conflicting types for 'des_ede2_cbc_decrypt'

    void des_ede2_cbc_decrypt(unsigned char *data, unsigned char *iv, const unsigned char *okey1, const unsigned char *okey2, int len)

cscrypt/des.c:821:6: note: previous definition of 'des_ede2_cbc_decrypt' was here

    void des_ede2_cbc_decrypt(uint8_t* data, const uint8_t* iv, const uint8_t* key1, const uint8_t* key2, int32_t len)

cscrypt/des.c: In function 'des_ede2_cbc_decrypt':
cscrypt/des.c:878:12: error: 'DES_ECS2_DECRYPT' undeclared (first use in this function)

    des(key1,DES_ECS2_DECRYPT,data);

cscrypt/des.c:878:29: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key1,DES_ECS2_DECRYPT,data);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

cscrypt/des.c:879:12: error: 'DES_ECS2_CRYPT' undeclared (first use in this function)

    des(key2,DES_ECS2_CRYPT,data);

cscrypt/des.c:879:27: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key2,DES_ECS2_CRYPT,data);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

cscrypt/des.c:880:29: warning: passing argument 3 of 'des' makes integer from pointer without a cast

    des(key1,DES_ECS2_DECRYPT,data);

cscrypt/des.c:680:6: note: expected 'int8_t' but argument is of type 'unsigned char *'

    void des(uint8_t* data, const uint32_t* schedule, int8_t encrypt)

**Comment by jahntheman** [comment]
fixed
