### ISSUE TITLE
dre 2

### ISSUE THREAD

**Issue by satxtreme** [oscam-emu/oscam-emu#152]
...When using AU keys, opens only 3 channels( pervyi, ntv, shop 24) not work overcrypt....fix it !

**Comment by jahntheman** [comment]
should be fixed now.
note that you have to add the 16 overcrypt key to SoftCam.key like this:

D 0 <number> <key>
example:
D 0 0 1122334455667788
...
D 0 F 1122334455667788

**Comment by megavolt85** [comment]
https://dropmefiles.com/tqNYy

**Comment by jahntheman** [comment]
some more fixes have been applied with 726
