### ISSUE TITLE
Source Stream Port 

### ISSUE THREAD

**Issue by vdrtuxnet** [oscam-emu/oscam-emu#153]
Hi,

It seems to be not possible to change the Source Stream Port in Stream Relay Config to any other than 8001.
Bug or feature?

**Comment by HolyGiraffe** [comment]
Hello, 
mus be a typo:
<TR><TD><A>Source Stream Port:</A></TD><TD><input name="strean_source_port" class="short" type="text" maxlength="5" value="##STREAM_SOURCE_PORT##"></TD></TR>

should be "stream_source_port"
i used oscam.conf to bypass this

**Comment by vdrtuxnet** [comment]
Hello,

THX!

You are right, just a typo.

**Comment by jahntheman** [comment]
thank you, fixed.
