### ISSUE TITLE
Does not work oscam-emu patch of v10919

### ISSUE THREAD

**Issue by commando2015** [oscam-emu/oscam-emu#154]
does not work oscam-emu patch of v10919
http://i.imgur.com/Pqu0wS3.jpg

oscam-emu not supported here

that is supported by 10918 and now you do not
but you made a mistake and correct make

10918 OK support oscam-emu (oscam-svn = oscam-emu.patch)
10919 NO support oscam-emu

http://i.imgur.com/MONCTNc.jpg

10900-10918 OK
http://i.imgur.com/3n0WOQU.jpg

Changed 105 minutes ago by Jan Gruuthuse 
scam-emu patch is external work ... ask for support in forum ... not ticket system.
oscam-emu patch: ​https://github.com/oscam-emu/oscam-emu/commits/master

**Comment by commando2015** [comment]
918 OK support oscam-emu (oscam-svn = oscam-emu.patch)

OR

ERROR LOG
failed to build oscam-svn 10936-mipsoe20-webif-oscam-emu-patched

apply patch oscam-emu.patch
patching file CMakeLists.txt
patching file config.h
patching file config.sh
Hunk #4 FAILED at 344.
1 out of 5 hunks FAILED -- saving rejects to file config.sh.rej
patching file cscrypt/md5.c
patching file cscrypt/md5.h
patching file csctapi/cardreaders.h
patching file ffdecsa/CMakeLists.txt
patching file ffdecsa/COPYING
patching file ffdecsa/Makefile
patching file ffdecsa/ffdecsa.c
patching file ffdecsa/ffdecsa.h
patching file ffdecsa/fftable.h
patching file ffdecsa/parallel_032_int.h
patching file ffdecsa/parallel_generic.h
patching file ffdecsa/parallel_std_def.h
patching file ffdecsa/stream.c
patching file globals.h
Hunk #1 succeeded at 421 (offset 17 lines).
Hunk #2 succeeded at 835 (offset 17 lines).
Hunk #3 succeeded at 965 (offset 17 lines).
Hunk #4 succeeded at 1627 (offset 27 lines).
Hunk #5 succeeded at 2085 (offset 39 lines).
Hunk #6 succeeded at 2258 (offset 42 lines).
patching file Makefile
patching file module-dvbapi.c
Hunk #1 succeeded at 1209 (offset 56 lines).
Hunk #2 succeeded at 1236 (offset 56 lines).
Hunk #3 succeeded at 3825 (offset 58 lines).
Hunk #4 succeeded at 3851 (offset 58 lines).
Hunk #5 succeeded at 5191 (offset 104 lines).
patching file module-dvbapi.h
Hunk #1 succeeded at 98 (offset 1 line).
patching file module-emulator-dre2overcrypt.c
patching file module-emulator-dre2overcrypt.h
patching file module-emulator-osemu.c
patching file module-emulator-osemu.h
patching file module-emulator-st20.c
patching file module-emulator-st20.h
patching file module-emulator-stream.c
patching file module-emulator-stream.h
patching file module-emulator.c
patching file module-newcamd-des.c
patching file module-newcamd-des.h
patching file module-stat.c
patching file module-webif-tpl.c
patching file module-webif.c
Hunk #2 FAILED at 120.
Hunk #3 succeeded at 939 (offset 2 lines).
Hunk #4 succeeded at 1365 (offset 2 lines).
Hunk #5 succeeded at 1806 (offset 2 lines).
Hunk #6 succeeded at 2363 (offset 6 lines).
Hunk #7 succeeded at 2390 (offset 6 lines).
Hunk #8 succeeded at 4070 (offset 10 lines).
Hunk #9 succeeded at 4590 (offset 10 lines).
Hunk #10 succeeded at 5995 (offset 10 lines).
Hunk #11 succeeded at 7485 (offset 19 lines).
1 out of 11 hunks FAILED -- saving rejects to file module-webif.c.rej
patching file oscam-chk.c
Hunk #1 succeeded at 706 (offset 1 line).
Hunk #2 succeeded at 742 (offset 1 line).
Hunk #3 succeeded at 975 (offset 1 line).
patching file oscam-config-global.c
Hunk #1 succeeded at 802 (offset 1 line).
Hunk #2 succeeded at 1081 (offset 1 line).
patching file oscam-config-reader.c
Hunk #2 succeeded at 446 (offset 44 lines).
Hunk #3 succeeded at 754 (offset 44 lines).
Hunk #4 succeeded at 889 (offset 46 lines).
patching file oscam-config.h
Hunk #2 succeeded at 56 (offset 1 line).
patching file oscam-emm.c
patching file oscam-string.c
Hunk #1 succeeded at 494 (offset 3 lines).
patching file oscam-string.h
patching file oscam.c
Hunk #3 succeeded at 1585 (offset 1 line).
Hunk #4 succeeded at 1759 (offset 1 line).
Hunk #5 succeeded at 1841 (offset 2 lines).
patching file reader-common.c
patching file readers.h
patching file webif/config/menu.html
patching file webif/config/menu_streamrelay.html
patching file webif/config/streamrelay.html
patching file webif/files/menu.html
Hunk #1 FAILED at 10.
Hunk #2 FAILED at 18.
2 out of 2 hunks FAILED -- saving rejects to file webif/files/menu.html.rej
patching file webif/files/menu_key.html
patching file webif/pages_index.txt
Hunk #3 succeeded at 179 (offset 2 lines).
patching file webif/readerconfig/readerconfig_emubit.html

+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 10936 target: mipsel-unknown-linux-gnu
| Tools:
| CROSS = /simplebuild/toolchains/mipsoe20/bin/mipsel-unknown-linux-gnu-
| CC = /simplebuild/toolchains/mipsoe20/bin/mipsel-unknown-linux-gnu-gcc
| Settings:
| CONF_DIR = /var/tuxbox/config
| CC_OPTS = -Os -ggdb -pipe -ffunction-sections -fdata-sections
| CC_WARN = -w
| CFLAGS =
| LDFLAGS = -Wl,--gc-sections -Wl,-rpath,/lib -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib -L/simplebuild/toolchains/mipsoe20/mipsel-unknown-linux-gnu/sysroot/usr/lib
| LIBS = -lpthread -ldl -lrt
| UseFlags =
| Config:
| Addons : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK CLOCKFIX WITH_EMU
| Protocols: CAMD33 CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
| Readers : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
| CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER
| Compiler : mipsel-unknown-linux-gnu-gcc (crosstool-NG 1.15.2) 4.6.3
| Config : build/mipsel-unknown-linux-gnu/config.mak
| Binary : ../archiv/oscam-svn10936-mipsoe20-webif-oscam-emu-patched
+-------------------------------------------------------------------------------
HOSTCC webif/pages_gen
GEN webif/pages.c
GEN Compressed 391732 template bytes into 163842 bytes. 227890 saved bytes (58.17%).
CC cscrypt/aes.c
CC cscrypt/bn_add.c
CC cscrypt/bn_asm.c
CC cscrypt/bn_ctx.c
CC cscrypt/bn_div.c
CC cscrypt/bn_exp.c
CC cscrypt/bn_lib.c
CC cscrypt/bn_mul.c
CC cscrypt/bn_print.c
CC cscrypt/bn_shift.c
CC cscrypt/bn_sqr.c
CC cscrypt/bn_word.c
CC cscrypt/mem.c
CC cscrypt/des.c
CC cscrypt/i_cbc.c
CC cscrypt/i_ecb.c
CC cscrypt/i_skey.c
CC cscrypt/md5.c
CC cscrypt/rc6.c
CC cscrypt/sha1.c
CC csctapi/atr.c
CC csctapi/icc_async.c
CC csctapi/io_serial.c
CC csctapi/protocol_t0.c
CC csctapi/protocol_t1.c
CC csctapi/ifd_db2com.c
CC csctapi/ifd_mp35.c
CC csctapi/ifd_phoenix.c
CC csctapi/ifd_sc8in1.c
CC csctapi/ifd_sci.c
CC csctapi/ifd_smargo.c
CC csctapi/ifd_stinger.c
CC minilzo/minilzo.c
CC module-anticasc.c
CC module-cacheex.c
CC module-camd33.c
CC module-camd35-cacheex.c
CC module-camd35.c
CC module-cccam-cacheex.c
CC module-cccam.c
CC module-cccshare.c
CC module-constcw.c
CC module-emulator.c
CC module-emulator-osemu.c
CC module-emulator-stream.c
CC module-emulator-st20.c
CC module-emulator-dre2overcrypt.c
CC ffdecsa/ffdecsa.c
CC module-csp.c
CC module-cw-cycle-check.c
CC module-dvbapi-chancache.c
CC module-dvbapi.c
CC module-gbox-helper.c
CC module-gbox-sms.c
CC module-gbox-cards.c
CC module-gbox.c
CC module-ird-guess.c
CC module-monitor.c
CC module-newcamd.c
CC module-newcamd-des.c
CC module-pandora.c
CC module-ghttp.c
CC module-radegast.c
CC module-scam.c
CC module-serial.c
CC module-stat.c
CC module-webif-lib.c
CC module-webif-tpl.c
CC module-webif.c
module-webif.c: In function 'send_oscam_files':
module-webif.c:5999:24: error: 'MNU_CFG_KEY' undeclared (first use in this function)
module-webif.c:5999:24: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [build/mipsel-unknown-linux-gnu/module-webif.o] Error 1
make: *** [all] Error 2

NO oscam-emu.patch OK
please fixed oscam-emu.patch

**Comment by jahntheman** [comment]
thank you, fixed.

**Comment by commando2015** [comment]
thanks @jahntheman

**Comment by commando2015** [comment]
10987 not ok

apply patch oscam-emu.patch
patching file CMakeLists.txt
patching file config.h
patching file config.sh
patching file cscrypt/md5.c
patching file cscrypt/md5.h
patching file csctapi/cardreaders.h
patching file ffdecsa/CMakeLists.txt
patching file ffdecsa/COPYING
patching file ffdecsa/Makefile
patching file ffdecsa/ffdecsa.c
patching file ffdecsa/ffdecsa.h
patching file ffdecsa/fftable.h
patching file ffdecsa/parallel_032_int.h
patching file ffdecsa/parallel_064_long.h
patching file ffdecsa/parallel_128_sse2.h
patching file ffdecsa/parallel_generic.h
patching file ffdecsa/parallel_std_def.h
patching file ffdecsa/stream.c
patching file globals.h
Hunk #1 succeeded at 420 (offset -1 lines).
Hunk #2 succeeded at 834 (offset -1 lines).
Hunk #3 succeeded at 964 (offset -1 lines).
Hunk #4 succeeded at 1650 (offset 23 lines).
Hunk #5 succeeded at 2117 (offset 32 lines).
Hunk #6 succeeded at 2297 (offset 36 lines).
patching file Makefile
patching file module-dvbapi.c
Hunk #1 succeeded at 1221 (offset 12 lines).
Hunk #2 succeeded at 1248 (offset 12 lines).
Hunk #3 succeeded at 3958 with fuzz 2 (offset 133 lines).
Hunk #4 succeeded at 3996 (offset 145 lines).
Hunk #5 succeeded at 5357 with fuzz 2 (offset 166 lines).
patching file module-dvbapi.h
patching file module-emulator-dre2overcrypt.c
patching file module-emulator-dre2overcrypt.h
patching file module-emulator-osemu.c
patching file module-emulator-osemu.h
patching file module-emulator-st20.c
patching file module-emulator-st20.h
patching file module-emulator-stream.c
patching file module-emulator-stream.h
patching file module-emulator.c
patching file module-newcamd-des.c
patching file module-newcamd-des.h
patching file module-stat.c
patching file module-webif-tpl.c
patching file module-webif.c
Hunk #2 FAILED at 123.
Hunk #3 succeeded at 947 (offset 5 lines).
Hunk #4 succeeded at 1378 (offset 5 lines).
Hunk #5 succeeded at 1819 (offset 5 lines).
Hunk #6 succeeded at 2376 (offset 5 lines).
Hunk #7 succeeded at 2403 (offset 5 lines).
Hunk #8 succeeded at 4083 (offset 5 lines).
Hunk #9 succeeded at 4603 (offset 5 lines).
Hunk #10 succeeded at 6033 with fuzz 2 (offset 8 lines).
Hunk #11 succeeded at 7506 (offset 8 lines).
1 out of 11 hunks FAILED -- saving rejects to file module-webif.c.rej
patching file oscam-chk.c
patching file oscam-config-global.c
Hunk #1 succeeded at 803 (offset 1 line).
Hunk #2 succeeded at 1083 (offset 1 line).
patching file oscam-config-reader.c
patching file oscam-config.h
Hunk #2 succeeded at 61 (offset 5 lines).
patching file oscam-ecm.c
patching file oscam-emm.c
patching file oscam-string.c
patching file oscam-string.h
patching file oscam.c
Hunk #5 succeeded at 1845 (offset 4 lines).
patching file reader-common.c
patching file readers.h
patching file webif/config/menu.html
patching file webif/config/menu_streamrelay.html
patching file webif/config/streamrelay.html
patching file webif/files/menu.html
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file webif/files/menu.html.rej
patching file webif/files/menu_softcamkey.html
patching file webif/pages_index.txt
Hunk #1 succeeded at 80 (offset 1 line).
Hunk #2 FAILED at 116.
Hunk #3 succeeded at 181 (offset 2 lines).
1 out of 3 hunks FAILED -- saving rejects to file webif/pages_index.txt.rej
patching file webif/readerconfig/readerconfig_emubit.html

+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 10987 target: mipsel-unknown-linux-gnu
| Tools:
|  CROSS    = /simplebuild/toolchains/mipsoe20/bin/mipsel-unknown-linux-gnu-
|  CC       = /simplebuild/toolchains/mipsoe20/bin/mipsel-unknown-linux-gnu-gcc
| Settings:
|  CONF_DIR = /var/tuxbox/config
|  CC_OPTS  = -Os -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -w
|  CFLAGS   = -fexpensive-optimizations -funroll-loops
|  LDFLAGS  = -Wl,--gc-sections -Wl,-rpath,/lib -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib -L/simplebuild/toolchains/mipsoe20/mipsel-unknown-linux-gnu/sysroot/usr/lib
|  LIBS     = -lpthread -ldl -lrt
|  UseFlags = 
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK CLOCKFIX WITH_EMU
|  Protocols: CAMD33 CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER
|  Compiler : mipsel-unknown-linux-gnu-gcc (crosstool-NG 1.15.2) 4.6.3
|  Config   : build/mipsel-unknown-linux-gnu/config.mak
|  Binary   : ../archiv/oscam-svn10987-mipsoe20-webif-oscam-emu-patched
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 393108 template bytes into 164534 bytes. 228574 saved bytes (58.15%).
CC	cscrypt/aes.c
CC	cscrypt/bn_add.c
CC	cscrypt/bn_asm.c
CC	cscrypt/bn_ctx.c
CC	cscrypt/bn_div.c
CC	cscrypt/bn_exp.c
CC	cscrypt/bn_lib.c
CC	cscrypt/bn_mul.c
CC	cscrypt/bn_print.c
CC	cscrypt/bn_shift.c
CC	cscrypt/bn_sqr.c
CC	cscrypt/bn_word.c
CC	cscrypt/mem.c
CC	cscrypt/des.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/md5.c
CC	cscrypt/rc6.c
CC	cscrypt/sha1.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	csctapi/ifd_db2com.c
CC	csctapi/ifd_mp35.c
CC	csctapi/ifd_phoenix.c
CC	csctapi/ifd_sc8in1.c
CC	csctapi/ifd_sci.c
CC	csctapi/ifd_smargo.c
CC	csctapi/ifd_stinger.c
CC	minilzo/minilzo.c
CC	module-anticasc.c
CC	module-cacheex.c
CC	module-camd33.c
CC	module-camd35-cacheex.c
CC	module-camd35.c
CC	module-cccam-cacheex.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-constcw.c
CC	module-emulator.c
CC	module-emulator-osemu.c
CC	module-emulator-stream.c
CC	module-emulator-st20.c
CC	module-emulator-dre2overcrypt.c
CC	ffdecsa/ffdecsa.c
CC	module-csp.c
CC	module-cw-cycle-check.c
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-ird-guess.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-newcamd-des.c
CC	module-pandora.c
CC	module-ghttp.c
CC	module-radegast.c
CC	module-scam.c
CC	module-serial.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
module-webif.c: In function 'send_oscam_files':
module-webif.c:6037:24: error: 'MNU_CFG_FSOFTCAMKEY' undeclared (first use in this function)
module-webif.c:6037:24: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [build/mipsel-unknown-linux-gnu/module-webif.o] Error 1
make: *** [all] Error 2
