### ISSUE TITLE
OSCam ver: 1.20-unstable_svn rev: 10991 build error

### ISSUE THREAD

**Issue by Matthias199** [oscam-emu/oscam-emu#170]
Hey if I try to compile this version with the patch there is in compile error

CC      module-webif.c
module-webif.c: In function 'send_oscam_files':
module-webif.c:6037: error: 'MNU_CFG_FSOFTCAMKEY' undeclared (first use in this function)
module-webif.c:6037: error: (Each undeclared identifier is reported only once
module-webif.c:6037: error: for each function it appears in.)
make[1]: *** [build/arm-none-linux-gnueabi-libusb/module-webif.o] Error 1
make: *** [all] Error 2

without the path is everything working fine any idea?

**Comment by QRS01** [comment]
The patch mentioned by joeusercz some issues ago, is still OK... 
Look for latest patch here: http://www.streamboard.tv/wbb2/thread.php?threadid=39010&threadview=1&hilight=&hilightuser=0&page=84#post551427

**Comment by Matthias199** [comment]
tanks but why there is not an master upgrade ?

**Comment by jahntheman** [comment]
fixed
