### ISSUE TITLE
bunch of compiling errors with latest oscam

### ISSUE THREAD

**Issue by ovidiu31** [oscam-emu/oscam-emu#171]
Hello J

below the errors encountered during compiling with latest oscam svn

module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:4028:5: error: ‘pvu_skip’ undeclared (first use in this function)
     pvu_skip = 1;
     ^
module-dvbapi.c:4028:5: note: each undeclared identifier is reported only once for each function it appears in
module-dvbapi.c:4030:8: error: ‘ecmlen’ undeclared (first use in this function)
     if(ecmlen > 0xb)
        ^
module-dvbapi.c:4333:14: error: invalid storage class for function ‘dvbapi_main_local’
 static void *dvbapi_main_local(void *cli)
              ^
module-dvbapi.c: In function ‘dvbapi_main_local’:
module-dvbapi.c:4354:10: warning: declaration of ‘len’ shadows a parameter [-Wshadow]
  ssize_t len = 0;
          ^
module-dvbapi.c:3949:88: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                                                                        ^
module-dvbapi.c:4730:20: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
       int32_t ret, pid;
                    ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c:4916:20: warning: declaration of ‘filter_num’ shadows a parameter [-Wshadow]
            int32_t filter_num = mbuf[5];
                    ^
module-dvbapi.c:3949:53: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                                     ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5023:6: warning: declaration of ‘dvbapi_write_cw’ shadows a global declaration [-Wshadow]
 void dvbapi_write_cw(int32_t demux_id, uchar *cw, int32_t pid)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:296:6: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_write_cw(int32_t demux_id, uchar *cw, int32_t idx);
      ^
module-dvbapi.c: In function ‘dvbapi_write_cw’:
module-dvbapi.c:5023:30: warning: declaration of ‘demux_id’ shadows a parameter [-Wshadow]
 void dvbapi_write_cw(int32_t demux_id, uchar *cw, int32_t pid)
                              ^
module-dvbapi.c:3949:35: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                   ^
module-dvbapi.c:5023:59: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 void dvbapi_write_cw(int32_t demux_id, uchar *cw, int32_t pid)
                                                           ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5121:6: warning: declaration of ‘delayer’ shadows a global declaration [-Wshadow]
 void delayer(ECM_REQUEST *er, uint32_t delay)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:315:6: warning: shadowed declaration is here [-Wshadow]
 void delayer(ECM_REQUEST *er, uint32_t delay);
      ^
module-dvbapi.c:5135:6: warning: declaration of ‘dvbapi_send_dcw’ shadows a global declaration [-Wshadow]
 void dvbapi_send_dcw(struct s_client *client, ECM_REQUEST *er)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:295:6: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_send_dcw(struct s_client *client, ECM_REQUEST *er);
      ^
module-dvbapi.c:5439:15: error: invalid storage class for function ‘isValidCW’
 static int8_t isValidCW(uint8_t *cw)
               ^
module-dvbapi.c:5452:6: warning: declaration of ‘dvbapi_write_ecminfo_file’ shadows a global declaration [-Wshadow]
 void dvbapi_write_ecminfo_file(struct s_client *client, ECM_REQUEST *er, uint8_t* lastcw0, uint8_t* lastcw1)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:319:6: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_write_ecminfo_file(struct s_client *client, ECM_REQUEST *er, uint8_t* lastcw0, uint8_t* lastcw1);
      ^
module-dvbapi.c:5637:7: warning: declaration of ‘dvbapi_start_handler’ shadows a global declaration [-Wshadow]
 void *dvbapi_start_handler(struct s_client *cl, uchar *UNUSED(mbuf), int32_t module_idx, void * (*_main_func)(void *))
       ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:317:7: warning: shadowed declaration is here [-Wshadow]
 void *dvbapi_start_handler(struct s_client *cl, uchar *mbuf, int32_t module_idx, void * (*_main_func)(void *));
       ^
module-dvbapi.c:5660:9: warning: declaration of ‘dvbapi_set_section_filter’ shadows a global declaration [-Wshadow]
 int32_t dvbapi_set_section_filter(int32_t demux_index, ECM_REQUEST *er, int32_t n)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:301:9: warning: shadowed declaration is here [-Wshadow]
 int32_t dvbapi_set_section_filter(int32_t demux_index, ECM_REQUEST *er, int32_t n);
         ^
module-dvbapi.c: In function ‘dvbapi_set_section_filter’:
module-dvbapi.c:5689:20: warning: declaration of ‘curpid’ shadows a previous local [-Wshadow]
  struct s_ecmpids *curpid = NULL;
                    ^
module-dvbapi.c:3952:20: warning: shadowed declaration is here [-Wshadow]
  struct s_ecmpids *curpid = NULL;
                    ^
module-dvbapi.c:5690:10: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
  int32_t pid = demux[demux_index].demux_fd[n].pidindex;
          ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5789:9: warning: declaration of ‘dvbapi_activate_section_filter’ shadows a global declaration [-Wshadow]
 int32_t dvbapi_activate_section_filter(int32_t demux_index, int32_t num, int32_t fd, int32_t pid, uchar *filter, uchar *mask)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:302:9: warning: shadowed declaration is here [-Wshadow]
 int32_t dvbapi_activate_section_filter(int32_t demux_index, int32_t num, int32_t fd, int32_t pid, uchar *filter, uchar *mask);
         ^
module-dvbapi.c: In function ‘dvbapi_activate_section_filter’:
module-dvbapi.c:5789:94: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 int32_t dvbapi_activate_section_filter(int32_t demux_index, int32_t num, int32_t fd, int32_t pid, uchar *filter, uchar *mask)
                                                                                              ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5875:9: warning: declaration of ‘dvbapi_check_ecm_delayed_delivery’ shadows a global declaration [-Wshadow]
 int32_t dvbapi_check_ecm_delayed_delivery(int32_t demux_index, ECM_REQUEST *er)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:303:9: warning: shadowed declaration is here [-Wshadow]
 int32_t dvbapi_check_ecm_delayed_delivery(int32_t demux_index, ECM_REQUEST *er);
         ^
module-dvbapi.c: In function ‘dvbapi_check_ecm_delayed_delivery’:
module-dvbapi.c:5895:20: warning: declaration of ‘curpid’ shadows a previous local [-Wshadow]
  struct s_ecmpids *curpid = NULL;
                    ^
module-dvbapi.c:3952:20: warning: shadowed declaration is here [-Wshadow]
  struct s_ecmpids *curpid = NULL;
                    ^
module-dvbapi.c:5897:10: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
  int32_t pid = demux[demux_index].demux_fd[filternum].pidindex;
          ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5911:9: warning: declaration of ‘dvbapi_get_filternum’ shadows a global declaration [-Wshadow]
 int32_t dvbapi_get_filternum(int32_t demux_index, ECM_REQUEST *er, int32_t type)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:304:9: warning: shadowed declaration is here [-Wshadow]
 int32_t dvbapi_get_filternum(int32_t demux_index, ECM_REQUEST *er, int32_t type);
         ^
module-dvbapi.c:5941:9: warning: declaration of ‘dvbapi_ca_setpid’ shadows a global declaration [-Wshadow]
 int32_t dvbapi_ca_setpid(int32_t demux_index, int32_t pid)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:305:9: warning: shadowed declaration is here [-Wshadow]
 int32_t dvbapi_ca_setpid(int32_t demux_index, int32_t pid);
         ^
module-dvbapi.c: In function ‘dvbapi_ca_setpid’:
module-dvbapi.c:5941:55: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 int32_t dvbapi_ca_setpid(int32_t demux_index, int32_t pid)
                                                       ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:5970:8: warning: declaration of ‘update_streampid_list’ shadows a global declaration [-Wshadow]
 int8_t update_streampid_list(uint8_t cadevice, uint16_t pid, int32_t idx)
        ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:307:8: warning: shadowed declaration is here [-Wshadow]
 int8_t update_streampid_list(uint8_t cadevice, uint16_t pid, int32_t idx);
        ^
module-dvbapi.c: In function ‘update_streampid_list’:
module-dvbapi.c:5970:57: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 int8_t update_streampid_list(uint8_t cadevice, uint16_t pid, int32_t idx)
                                                         ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6003:8: warning: declaration of ‘remove_streampid_from_list’ shadows a global declaration [-Wshadow]
 int8_t remove_streampid_from_list(uint8_t cadevice, uint16_t pid, int32_t idx)
        ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:308:8: warning: shadowed declaration is here [-Wshadow]
 int8_t remove_streampid_from_list(uint8_t cadevice, uint16_t pid, int32_t idx);
        ^
module-dvbapi.c: In function ‘remove_streampid_from_list’:
module-dvbapi.c:6003:62: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 int8_t remove_streampid_from_list(uint8_t cadevice, uint16_t pid, int32_t idx)
                                                              ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6057:6: warning: declaration of ‘disable_unused_streampids’ shadows a global declaration [-Wshadow]
 void disable_unused_streampids(int16_t demux_id)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:309:6: warning: shadowed declaration is here [-Wshadow]
 void disable_unused_streampids(int16_t demux_id);
      ^
module-dvbapi.c: In function ‘disable_unused_streampids’:
module-dvbapi.c:6057:40: warning: declaration of ‘demux_id’ shadows a parameter [-Wshadow]
 void disable_unused_streampids(int16_t demux_id)
                                        ^
module-dvbapi.c:3949:35: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                   ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6122:8: warning: declaration of ‘is_ca_used’ shadows a global declaration [-Wshadow]
 int8_t is_ca_used(uint8_t cadevice, int32_t pid)
        ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:310:8: warning: shadowed declaration is here [-Wshadow]
 int8_t is_ca_used(uint8_t cadevice, int32_t pid);
        ^
module-dvbapi.c: In function ‘is_ca_used’:
module-dvbapi.c:6122:45: warning: declaration of ‘pid’ shadows a previous local [-Wshadow]
 int8_t is_ca_used(uint8_t cadevice, int32_t pid)
                                             ^
module-dvbapi.c:3953:10: warning: shadowed declaration is here [-Wshadow]
  int32_t pid = demux[demux_id].demux_fd[filter_num].pidindex;
          ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6162:13: warning: declaration of ‘dvbapi_get_client_name’ shadows a global declaration [-Wshadow]
 const char *dvbapi_get_client_name(void)
             ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:311:13: warning: shadowed declaration is here [-Wshadow]
 const char *dvbapi_get_client_name(void);
             ^
module-dvbapi.c:6167:6: warning: declaration of ‘check_add_emmpid’ shadows a global declaration [-Wshadow]
 void check_add_emmpid(int32_t demux_index, uchar *filter, int32_t l, int32_t emmtype)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:316:6: warning: shadowed declaration is here [-Wshadow]
 void check_add_emmpid(int32_t demux_index, uchar *filter, int32_t l, int32_t emmtype);
      ^
module-dvbapi.c:6213:6: warning: declaration of ‘rotate_emmfilter’ shadows a global declaration [-Wshadow]
 void rotate_emmfilter(int32_t demux_id)
      ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:312:6: warning: shadowed declaration is here [-Wshadow]
 void rotate_emmfilter(int32_t demux_id);
      ^
module-dvbapi.c: In function ‘rotate_emmfilter’:
module-dvbapi.c:6213:31: warning: declaration of ‘demux_id’ shadows a parameter [-Wshadow]
 void rotate_emmfilter(int32_t demux_id)
                               ^
module-dvbapi.c:3949:35: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                   ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6293:9: warning: declaration of ‘filtermatch’ shadows a global declaration [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len)
         ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:313:9: warning: shadowed declaration is here [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len);
         ^
module-dvbapi.c: In function ‘filtermatch’:
module-dvbapi.c:6293:28: warning: declaration of ‘buffer’ shadows a parameter [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len)
                            ^
module-dvbapi.c:3949:72: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                                                        ^
module-dvbapi.c:6293:44: warning: declaration of ‘filter_num’ shadows a parameter [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len)
                                            ^
module-dvbapi.c:3949:53: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                                     ^
module-dvbapi.c:6293:64: warning: declaration of ‘demux_id’ shadows a parameter [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len)
                                                                ^
module-dvbapi.c:3949:35: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                   ^
module-dvbapi.c:6293:82: warning: declaration of ‘len’ shadows a parameter [-Wshadow]
 int32_t filtermatch(uchar *buffer, int32_t filter_num, int32_t demux_id, int32_t len)
                                                                                  ^
module-dvbapi.c:3949:88: warning: shadowed declaration is here [-Wshadow]
 void dvbapi_process_input(int32_t demux_id, int32_t filter_num, uchar *buffer, int32_t len)
                                                                                        ^
module-dvbapi.c: In function ‘dvbapi_process_input’:
module-dvbapi.c:6324:10: warning: declaration of ‘dvbapi_get_client_proto_version’ shadows a global declaration [-Wshadow]
 uint16_t dvbapi_get_client_proto_version(void)
          ^
In file included from module-dvbapi.c:7:0:
module-dvbapi.h:314:10: warning: shadowed declaration is here [-Wshadow]
 uint16_t dvbapi_get_client_proto_version(void);
          ^
module-dvbapi.c:6349:1: error: expected declaration or statement at end of input
 }
 ^
make[1]: *** [build/x86_64-redhat-linux/module-dvbapi.o] Error 1
make: *** [all] Error 2
[root@localhost oscam-svn]#

**Comment by jahntheman** [comment]
fixed
