### ISSUE TITLE
No audio in channels that has Teletext support.

### ISSUE THREAD

**Issue by nikkijd** [oscam-emu/oscam-emu#178]
oscam version:
oscam-svn10982-openpli40-webif-oscam-emu-pvu-aud-sub-tracks

satellite: 166E 3980 H 27690-3/4
STB: DM800se Openpli4 w/ gstreamer 1.6

Tested in other stb openbox x5, z5 and audio works ok.

Note: some channels that has TELETEXT sub has audio. but majority dont have audio

**Comment by jahntheman** [comment]
Possible fix added with v728.
