### ISSUE TITLE
Same Sid For Biss Not Working

### ISSUE THREAD

**Issue by budiarno** [oscam-emu/oscam-emu#188]
Hi,
Tried two same sid for the biss:
2600@000000/0000/0001/0D:F4EB3CBB30C0EE9ABBF612F25569E042): found (32 ms) 
But it's detected the wrong keys in the end, so picture is still blank.

Would you make the biss format with PMT Pid instead of the ECM Pid, for example like this:
F ServiceID-PmtPID 00 Key
F ServiceID-PmtPID 01 Key

That way seems look promising. Thank you.

**Comment by jahntheman** [comment]
Please use the constcw reader in oscam or oscam-emu.
Two BISS keys with same sid is not possible with OSEmu.

**Comment by loxel** [comment]
Oscam Ymod has Onid : Sid : VPid can here also to so could I do?
