### ISSUE TITLE
After watching PVU Channels, normal crypted channels are blackscreened, but ECM is correct (OE2.2)

### ISSUE THREAD

**Issue by satdxler** [oscam-emu/oscam-emu#195]
hello,

I got a problem with my OE2.2 Dreambox with the latest oscam-osemu.

After sucessfully encrypted pvu channel, I am not able to watch any other crypted system.
Only a reboot can fix the problem.

Please fix that :)

**Comment by vdrtuxnet** [comment]
That issue is not oscam-emu related, it is a Dreambox driver issue.

DMM need to fix their chip-set driver.
