### ISSUE TITLE
Prioritizing EMU 

### ISSUE THREAD

**Issue by mihaip1948** [oscam-emu/oscam-emu#198]
Must find a way to activate first EMU then proxies lines reffering same caid and provid  !!! 
this because now Oscam preffers proxies to EMU ! and is trying to open from proxy even 
the ECM is far too long ...

**Comment by mihaip1948** [comment]
Can we set a reader , particulary EMU , to be
the first into evaluation process ?

**Comment by jahntheman** [comment]
you can set priorities with oscam settings, please check oscam wiki
