### ISSUE TITLE
Cannot Complie with R11296 - Who can Update the Patch here?

### ISSUE THREAD

**Issue by FCS001FCS** [oscam-emu/oscam-emu#220]
See [http://www.streamboard.tv/wbb2/thread.php?postid=568917#post568917](url) for details of the problem and the errors that occur. OSCAM R11296 will not compile with oscam-emu patch from here using SimpleBuild 2.

**Comment by gorgone** [comment]
use simplebuild 3 and my github patch

**Comment by FCS001FCS** [comment]
Ok, thanks a lot.
