### ISSUE TITLE
rev 11310

### ISSUE THREAD

**Issue by mavroskoufis** [oscam-emu/oscam-emu#222]
I tray to compile with 
make CROSS=$TOOLCHAIN/bin/mipsel-tuxbox-linux-gnu- USE_SSL=1
and have this ERROR
module-webif.c: In function 'send_oscam_files':
module-webif.c:6296:24: error: 'MNU_CFG_FSOFTCAMKEY' undeclared (first use in this function)
   { "SoftCam.Key",     MNU_CFG_FSOFTCAMKEY,FTYPE_CONFIG }, // id 19

module-webif.c:6296:24: note: each undeclared identifier is reported only once for each function it appears in
Makefile:437: recipe for target 'build/mipsel-tuxbox-linux-gnu-ssl/module-webif.o' failed
make[1]: *** [build/mipsel-tuxbox-linux-gnu-ssl/module-webif.o] Error 1
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2
THANKS

**Comment by sculpneo** [comment]
same issue

**Comment by sculpneo** [comment]
it works, thank you

**Comment by mavroskoufis** [comment]
No for me with 
oscam-emu.patch
same error

**Comment by nautilus7** [comment]
You're are not using my patch from the pull request.

This is the file:  https://github.com/nautilus7/oscam-emu/blob/tandberg-ecm-emm-fix/oscam-emu.patch

**Comment by sculpneo** [comment]
https://github.com/nautilus7/oscam-emu/archive/tandberg-ecm-emm-fix.zip

**Comment by mavroskoufis** [comment]
Thanks Works !!!!
