### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by messi89** [oscam-emu/oscam-emu#226]
`
appliquer patch oscam-emu.patch
patching file CMakeLists.txt
patching file config.h
patching file config.sh
patching file cscrypt/md5.c
patching file cscrypt/md5.h
patching file csctapi/cardreaders.h
patching file ffdecsa/CMakeLists.txt
patching file ffdecsa/COPYING
patching file ffdecsa/Makefile
patching file ffdecsa/ffdecsa.c
patching file ffdecsa/ffdecsa.h
patching file ffdecsa/fftable.h
patching file ffdecsa/parallel_032_int.h
patching file ffdecsa/parallel_064_long.h
patching file ffdecsa/parallel_128_sse2.h
patching file ffdecsa/parallel_generic.h
patching file ffdecsa/parallel_std_def.h
patching file ffdecsa/stream.c
patching file globals.h
patching file Makefile
patching file module-dvbapi.c
patching file module-dvbapi.h
patching file module-emulator-osemu.c
patching file module-emulator-osemu.h
patching file module-emulator-stream.c
patching file module-emulator-stream.h
patching file module-emulator.c
patching file module-newcamd-des.c
patching file module-newcamd-des.h
patching file module-newcamd.c
patching file module-stat.c
patching file module-webif-tpl.c
patching file module-webif.c
patching file oscam-chk.c
patching file oscam-config-global.c
patching file oscam-config-reader.c
patching file oscam-config.h
patching file oscam-ecm.c
patching file oscam-emm.c
patching file oscam-string.c
patching file oscam-string.h
patching file oscam.c
patching file reader-common.c
patching file readers.h
patching file webif/config/dvbapi.html
patching file webif/config/menu.html
patching file webif/config/menu_streamrelay.html
patching file webif/config/streamrelay.html
patching file webif/files/menu.html
patching file webif/files/menu_softcamkey.html
patching file webif/pages_index.txt
patching file webif/readerconfig/readerconfig_emubit.html

+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 11330 target: x86_64-linux-gnu
| Tools:
|  CROSS    = 
|  CC       = gcc
| Settings:
|  CONF_DIR = /usr/local/etc
|  CC_OPTS  = -Os -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -w
|  CFLAGS   = -fexpensive-optimizations -mmmx -msse -msse2 -msse3
|  LDFLAGS  = -Wl,--gc-sections -lz -Wl,-rpath,/usr/lib
|  LIBS     = -lpthread -ldl -lrt
|  UseFlags = 
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK CLOCKFIX WITH_EMU
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : 
|  Compiler : gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
|  Config   : build/x86_64-linux-gnu/config.mak
|  Binary   : ../archiv/oscam-svn11330-ubuntu-x86_64-webif-oscam-emu-patched
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 438552 template bytes into 175523 bytes. 263029 saved bytes (59.98%).
CC	cscrypt/bn_add.c
CC	cscrypt/aes.c
CC	cscrypt/bn_asm.c
CC	cscrypt/bn_ctx.c
CC	cscrypt/bn_div.c
CC	cscrypt/bn_exp.c
CC	cscrypt/bn_lib.c
CC	cscrypt/bn_mul.c
CC	cscrypt/bn_print.c
CC	cscrypt/bn_shift.c
CC	cscrypt/bn_sqr.c
CC	cscrypt/bn_word.c
CC	cscrypt/mem.c
CC	cscrypt/des.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/md5.c
CC	cscrypt/rc6.c
CC	cscrypt/sha1.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	minilzo/minilzo.c
CC	module-anticasc.c
CC	module-cacheex.c
CC	module-camd35-cacheex.c
CC	module-camd35.c
CC	module-cccam-cacheex.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-constcw.c
CC	module-emulator.c
module-emulator.c:859:16: error: redefinition of ‘emu_do_ecm’
 static int32_t emu_do_ecm(struct s_reader *rdr, const struct ecm_request_t *er, struct s_ecm_answer *ea)
                ^
module-emulator.c:15:16: note: previous definition of ‘emu_do_ecm’ was here
 static int32_t emu_do_ecm(struct s_reader *rdr, const struct ecm_request_t *er, struct s_ecm_answer *ea)
                ^
module-emulator.c:878:16: error: redefinition of ‘emu_do_emm’
 static int32_t emu_do_emm(struct s_reader *rdr, struct emm_packet_t *emm)
                ^
module-emulator.c:34:16: note: previous definition of ‘emu_do_emm’ was here
 static int32_t emu_do_emm(struct s_reader *rdr, struct emm_packet_t *emm)
                ^
module-emulator.c:908:16: error: redefinition of ‘emu_card_info’
 static int32_t emu_card_info(struct s_reader *rdr) {
                ^
module-emulator.c:64:16: note: previous definition of ‘emu_card_info’ was here
 static int32_t emu_card_info(struct s_reader *rdr) {
                ^
module-emulator.c:913:16: error: redefinition of ‘emu_card_init’
 static int32_t emu_card_init(struct s_reader *UNUSED(rdr), struct s_ATR *UNUSED(atr))
                ^
module-emulator.c:69:16: note: previous definition of ‘emu_card_init’ was here
 static int32_t emu_card_init(struct s_reader *UNUSED(rdr), struct s_ATR *UNUSED(atr))
                ^
module-emulator.c:916:16: error: redefinition of ‘emu_get_emm_filter’
 static int32_t emu_get_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **UNUSED(emm_filters), unsigned int *UNUSED(filter_count))
                ^
module-emulator.c:72:16: note: previous definition of ‘emu_get_emm_filter’ was here
 static int32_t emu_get_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **UNUSED(emm_filters), unsigned int *UNUSED(filter_count))
                ^
module-emulator.c:920:9: error: redefinition of ‘emu_get_via3_emm_type’
 int32_t emu_get_via3_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:76:9: note: previous definition of ‘emu_get_via3_emm_type’ was here
 int32_t emu_get_via3_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:968:9: error: redefinition of ‘emu_get_ird2_emm_type’
 int32_t emu_get_ird2_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:124:9: note: previous definition of ‘emu_get_ird2_emm_type’ was here
 int32_t emu_get_ird2_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:1012:9: error: redefinition of ‘emu_get_pvu_emm_type’
 int32_t emu_get_pvu_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:168:9: note: previous definition of ‘emu_get_pvu_emm_type’ was here
 int32_t emu_get_pvu_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:1028:9: error: redefinition of ‘emu_get_dre2_emm_type’
 int32_t emu_get_dre2_emm_type(EMM_PACKET *ep, struct s_reader *UNUSED(rdr))
         ^
module-emulator.c:184:9: note: previous definition of ‘emu_get_dre2_emm_type’ was here
 int32_t emu_get_dre2_emm_type(EMM_PACKET *ep, struct s_reader *UNUSED(rdr))
         ^
module-emulator.c:1065:9: error: redefinition of ‘emu_get_tan_emm_type’
 int32_t emu_get_tan_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:221:9: note: previous definition of ‘emu_get_tan_emm_type’ was here
 int32_t emu_get_tan_emm_type(EMM_PACKET *ep, struct s_reader *rdr)
         ^
module-emulator.c:1079:16: error: redefinition of ‘emu_get_emm_type’
 static int32_t emu_get_emm_type(struct emm_packet_t *ep, struct s_reader *rdr)
                ^
module-emulator.c:235:16: note: previous definition of ‘emu_get_emm_type’ was here
 static int32_t emu_get_emm_type(struct emm_packet_t *ep, struct s_reader *rdr)
                ^
module-emulator.c:1105:16: error: redefinition of ‘emu_get_via3_emm_filter’
 static int32_t emu_get_via3_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid))
                ^
module-emulator.c:261:16: note: previous definition of ‘emu_get_via3_emm_filter’ was here
 static int32_t emu_get_via3_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid))
                ^
module-emulator.c:1133:16: error: redefinition of ‘emu_get_ird2_emm_filter’
 static int32_t emu_get_ird2_emm_filter(struct s_reader* rdr, struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t UNUSED(provid))
                ^
module-emulator.c:289:16: note: previous definition of ‘emu_get_ird2_emm_filter’ was here
 static int32_t emu_get_ird2_emm_filter(struct s_reader* rdr, struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t UNUSED(provid))
                ^
module-emulator.c:1202:16: error: redefinition of ‘emu_get_pvu_emm_filter’
 static int32_t emu_get_pvu_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid), uint16_t srvid)
                ^
module-emulator.c:358:16: note: previous definition of ‘emu_get_pvu_emm_filter’ was here
 static int32_t emu_get_pvu_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid), uint16_t srvid)
                ^
module-emulator.c:1244:16: error: redefinition of ‘emu_get_dre2_emm_filter’
 static int32_t emu_get_dre2_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t provid)
                ^
module-emulator.c:400:16: note: previous definition of ‘emu_get_dre2_emm_filter’ was here
 static int32_t emu_get_dre2_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t provid)
                ^
module-emulator.c:1301:16: error: redefinition of ‘emu_get_tan_emm_filter’
 static int32_t emu_get_tan_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid))
                ^
module-emulator.c:457:16: note: previous definition of ‘emu_get_tan_emm_filter’ was here
 static int32_t emu_get_tan_emm_filter(struct s_reader *UNUSED(rdr), struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t UNUSED(caid), uint32_t UNUSED(provid))
                ^
module-emulator.c:1337:16: error: redefinition of ‘emu_get_emm_filter_adv’
 static int32_t emu_get_emm_filter_adv(struct s_reader *rdr, struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t provid, uint16_t srvid)
                ^
module-emulator.c:493:16: note: previous definition of ‘emu_get_emm_filter_adv’ was here
 static int32_t emu_get_emm_filter_adv(struct s_reader *rdr, struct s_csystem_emm_filter **emm_filters, unsigned int *filter_count, uint16_t caid, uint32_t provid, uint16_t srvid)
                ^
module-emulator.c:1363:27: error: redefinition of ‘reader_emu’
 const struct s_cardsystem reader_emu =
                           ^
module-emulator.c:519:27: note: previous definition of ‘reader_emu’ was here
 const struct s_cardsystem reader_emu =
                           ^
module-emulator.c:1380:13: error: redefinition of ‘emu_add_entitlement’
 static void emu_add_entitlement(struct s_reader *rdr, uint16_t caid, uint32_t provid, uint8_t *key, char *keyName, uint32_t keyLength, uint8_t isData)
             ^
module-emulator.c:536:13: note: previous definition of ‘emu_add_entitlement’ was here
 static void emu_add_entitlement(struct s_reader *rdr, uint16_t caid, uint32_t provid, uint8_t *key, char *keyName, uint32_t keyLength, uint8_t isData)
             ^
module-emulator.c:1407:16: error: redefinition of ‘oneByte’
 static uint8_t oneByte = 0x01;
                ^
module-emulator.c:563:16: note: previous definition of ‘oneByte’ was here
 static uint8_t oneByte = 0x01;
                ^
module-emulator.c:1409:13: error: redefinition of ‘refresh_entitlements’
 static void refresh_entitlements(struct s_reader *reader)
             ^
module-emulator.c:565:13: note: previous definition of ‘refresh_entitlements’ was here
 static void refresh_entitlements(struct s_reader *reader)
             ^
module-emulator.c:1464:13: error: redefinition of ‘set_hexserial_to_version’
 static void set_hexserial_to_version(struct s_reader *rdr)
             ^
module-emulator.c:620:13: note: previous definition of ‘set_hexserial_to_version’ was here
 static void set_hexserial_to_version(struct s_reader *rdr)
             ^
module-emulator.c:1477:13: error: redefinition of ‘set_prids’
 static void set_prids(struct s_reader *rdr)
             ^
module-emulator.c:633:13: note: previous definition of ‘set_prids’ was here
 static void set_prids(struct s_reader *rdr)
             ^
module-emulator.c:1493:9: error: redefinition of ‘get_emu_prids_for_caid’
 FILTER* get_emu_prids_for_caid(struct s_reader *rdr, uint16_t caid)
         ^
module-emulator.c:649:9: note: previous definition of ‘get_emu_prids_for_caid’ was here
 FILTER* get_emu_prids_for_caid(struct s_reader *rdr, uint16_t caid)
         ^
module-emulator.c:1508:16: error: redefinition of ‘EMU_Init’
 static int32_t EMU_Init(struct s_reader *reader)
                ^
module-emulator.c:664:16: note: previous definition of ‘EMU_Init’ was here
 static int32_t EMU_Init(struct s_reader *reader)
                ^
module-emulator.c:1590:16: error: redefinition of ‘EMU_GetStatus’
 static int32_t EMU_GetStatus(struct s_reader *UNUSED(reader), int32_t *in) { *in = 1; return CR_OK; }
                ^
module-emulator.c:746:16: note: previous definition of ‘EMU_GetStatus’ was here
 static int32_t EMU_GetStatus(struct s_reader *UNUSED(reader), int32_t *in) { *in = 1; return CR_OK; }
                ^
module-emulator.c:1591:16: error: redefinition of ‘EMU_Activate’
 static int32_t EMU_Activate(struct s_reader *UNUSED(reader), struct s_ATR *UNUSED(atr)) { return CR_OK; }
                ^
module-emulator.c:747:16: note: previous definition of ‘EMU_Activate’ was here
 static int32_t EMU_Activate(struct s_reader *UNUSED(reader), struct s_ATR *UNUSED(atr)) { return CR_OK; }
                ^
module-emulator.c:1592:16: error: redefinition of ‘EMU_Transmit’
 static int32_t EMU_Transmit(struct s_reader *UNUSED(reader), uint8_t *UNUSED(buffer), uint32_t UNUSED(size),
                ^
module-emulator.c:748:16: note: previous definition of ‘EMU_Transmit’ was here
 static int32_t EMU_Transmit(struct s_reader *UNUSED(reader), uint8_t *UNUSED(buffer), uint32_t UNUSED(size),
                ^
module-emulator.c:1594:16: error: redefinition of ‘EMU_Receive’
 static int32_t EMU_Receive(struct s_reader *UNUSED(reader), uint8_t *UNUSED(buffer), uint32_t UNUSED(size),
                ^
module-emulator.c:750:16: note: previous definition of ‘EMU_Receive’ was here
 static int32_t EMU_Receive(struct s_reader *UNUSED(reader), uint8_t *UNUSED(buffer), uint32_t UNUSED(size),
                ^
module-emulator.c:1596:16: error: redefinition of ‘EMU_Close’
 static int32_t EMU_Close(struct s_reader *UNUSED(reader)) { return CR_OK; }
                ^
module-emulator.c:752:16: note: previous definition of ‘EMU_Close’ was here
 static int32_t EMU_Close(struct s_reader *UNUSED(reader)) { return CR_OK; }
                ^
module-emulator.c:1597:16: error: redefinition of ‘EMU_write_settings’
 static int32_t EMU_write_settings(struct s_reader *UNUSED(reader), struct s_cardreader_settings *UNUSED(s)) { return CR_OK; }
                ^
module-emulator.c:753:16: note: previous definition of ‘EMU_write_settings’ was here
 static int32_t EMU_write_settings(struct s_reader *UNUSED(reader), struct s_cardreader_settings *UNUSED(s)) { return CR_OK; }
                ^
module-emulator.c:1598:16: error: redefinition of ‘EMU_card_write’
 static int32_t EMU_card_write(struct s_reader *UNUSED(pcsc_reader),const uchar *UNUSED(buf) ,uint8_t *UNUSED(cta_res),
                ^
module-emulator.c:754:16: note: previous definition of ‘EMU_card_write’ was here
 static int32_t EMU_card_write(struct s_reader *UNUSED(pcsc_reader),const uchar *UNUSED(buf) ,uint8_t *UNUSED(cta_res),
                ^
module-emulator.c:1600:16: error: redefinition of ‘EMU_set_protocol’
 static int32_t EMU_set_protocol(struct s_reader *UNUSED(rdr),uint8_t *UNUSED(params),uint32_t *UNUSED(length),
                ^
module-emulator.c:756:16: note: previous definition of ‘EMU_set_protocol’ was here
 static int32_t EMU_set_protocol(struct s_reader *UNUSED(rdr),uint8_t *UNUSED(params),uint32_t *UNUSED(length),
                ^
module-emulator.c:1603:27: error: redefinition of ‘cardreader_emu’
 const struct s_cardreader cardreader_emu =
                           ^
module-emulator.c:759:27: note: previous definition of ‘cardreader_emu’ was here
 const struct s_cardreader cardreader_emu =
                           ^
module-emulator.c:1619:6: error: redefinition of ‘add_emu_reader’
 void add_emu_reader(void)
      ^
module-emulator.c:775:6: note: previous definition of ‘add_emu_reader’ was here
 void add_emu_reader(void)
      ^
make[1]: *** [build/x86_64-linux-gnu/module-emulator.o] Erreur 1
make[1]: *** Attente des tâches non terminées....
make: *** [all] Erreur 2`

**Comment by messi89** [comment]
oscam 11330

**Comment by nautilus7** [comment]
Something is wrong on your part. Works fine here.

**Comment by messi89** [comment]
@nautilus7 I will try to clean and checkout oscam again.

**Comment by messi89** [comment]
fixed by clean/checkout oscam

**Comment by nautilus7** [comment]
ok thanks.
