### ISSUE TITLE
Oscam-svn11340 help....

### ISSUE THREAD

**Issue by udz99** [oscam-emu/oscam-emu#229]
maybe im ask out of the box, but im still confusing about my oscam.....
i just compiled with the oscam-svn11340 version patched with emu but, my (reader) emulator cannot Get EMM key, is there any setting or config to get EMM key worked just like im running in oscam-svn11279 (old one)....

**oscam-svn11279 log**
2017/01/15 13:50:10 359464FE c   (dvbapi) Demuxer 0 restarting decodingrequests after 1 ms with 1 enabled and 0 disabled ecmpids!
2017/01/15 13:50:10 359464FE c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 1010 PROVID 000000 ECMPID 07D1 ANY CHID PMTPID 0100 VPID 0191
2017/01/15 13:50:10 359464FE c      (ecm) dvbapi (1010@000000/0000/0001/2B:9C22C36ADB331679931E2C88B43B0C94): rejected group (1 ms) - IMG Asia (no matching reader)
2017/01/15 13:50:10 359464FE c [Emu] GetEMMKey: key_index(40), keySet: 1
2017/01/15 13:50:10 359464FE c      (ecm) dvbapi (1010@000000/0000/0001/2B:9C22C36ADB331679931E2C88B43B0C94): rejected group (1 ms) - IMG Asia (no matching reader)
2017/01/15 13:50:10 359464FE c   (dvbapi) Demuxer 0 restarting decodingrequests after 0 ms with 1 enabled and 0 disabled ecmpids!
2017/01/15 13:50:10 359464FE c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 1010 PROVID 000000 ECMPID 07D1 ANY CHID PMTPID 0100 VPID 0191
2017/01/15 13:50:10 1CECC7AE r [Emu] GetEMMKey: key_index(21), keySet: 2
2017/01/15 13:50:10 1CECC7AE r [Emu] error: GetEMMKey: ram key 21 not yet available
2017/01/15 13:50:10 1CECC7AE r   (reader) emulator [emu] dvbapi emmtype=global, len=72 (hex: 0x48), cnt=1: written (0 ms)
2017/01/15 13:50:10 359464FE c   (reader) emulator [emu] Successfully added EMM to /etc/tuxbox/config/emulator_global_emm.log

still cannot set my newest oscam like that...

**Comment by oscam-emu** [comment]
Delete your emulator reader and restart oscam.

Nothing has changed in the code, so it's an issue on your side.
