### ISSUE TITLE
Enhancement code correctly on finding the right BISS key

### ISSUE THREAD

**Issue by ceco2000** [oscam-emu/oscam-emu#234]
Hi to all developers
  I would like to ask there is an option to improve the code on the right finding the right biss key. The situation now is such that if they are described more key's to / 00011FFF / is obtained mess and the channel remains not decoded even when described the correct key.

Thank you in advance!

**Comment by oscam-emu** [comment]
Hi, you can always use the constant cw reader (built in oscam) to describe in detail each channel.

**Comment by ceco2000** [comment]
Hi
For me, your answer is not the solution, I think oscam-emu could replace constant.cw module completely.
However, many thanks.

**Comment by oscam-emu** [comment]
constant cw protocol is built is in oscam. Why do you ask from an add-on (oscam-emu) for a feature that is already provided without the add-on?

Why can't you use the constant cw protocol?

**Comment by ceco2000** [comment]
The explanation and very simple, work and care only one key file.
