### ISSUE TITLE
Cosmetic error in the webif user account settings

### ISSUE THREAD

**Issue by cb3hn** [oscam-emu/oscam-emu#235]
Hi,

in section allowed time frame webif, I see this visible code: DAY@HH:MM-HH:MM[,HH:MM-HH:MM[;DAY@HH:MM-HH:MM[,HH:MM-HH:MM]]]
where DAY=SUN,MON,TUE,WED,THU,FRI,SAT,ALL

svn#: 11364
Hardware: Raspberry Pi 3
OS: Ubuntu Classic Server 16.04 by Ryan Finnie
Compiler : gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4)

**Comment by oscam-emu** [comment]
This is oscam related. Not emu related.

I am not sure this is done by mistake, though.
