### ISSUE TITLE
PowerVU EMM key capacity

### ISSUE THREAD

**Issue by badproject** [oscam-emu/oscam-emu#236]
My SoftCam.Key have more than 100 EMM Keys for mixed groups. I see all keys at reader entitlements.
But oscam-emu use only first 64 EMM keys when autoroll.

**Comment by oscam-emu** [comment]
Hi, It seems there's no limitation in the code. It might be a driver issue. 100 keys are way too many.

Try to give a log of oscam-emu with debug level 192 (64=emm + 128=dvbapi).  It might indicate what's wrong.

**Comment by badproject** [comment]
File attached.

[oscam.log.zip](https://github.com/oscam-emu/oscam-emu/files/959721/oscam.log.zip)

**Comment by PeterMaxu** [comment]
Problem still exist in the actual version, tested with openpli 6.2 on vu solo 4k.

**Comment by nautilus7** [comment]
I believe I found the problem! Would you like a test build to see if it works? What is your box (image and cpu architecture)?

**Comment by oscam-emu** [comment]
@badproject , @PeterMaxu I believe we found the problem! Would you like a test build to see if it works? What is your box (image and cpu architecture)?

**Comment by oscam-emu** [comment]
https://github.com/oscam-emu/oscam-emu/issues/286

**Comment by oscam-emu** [comment]
I am not sure how you came into the number of 64 emm keys max. My calculations say that there is a limit of 16 emm keys per group id.

While 16 keys are not that low, I am thinking of increasing it to 32 emm keys per group id.

**Comment by oscam-emu** [comment]
With emu r776 emm key capacity was increased to 32 per group id. It should be enough.
