### ISSUE TITLE
Oscam Emu doesn't patch

### ISSUE THREAD

**Issue by Bigsailor69** [oscam-emu/oscam-emu#237]
Hello, with the last version of oscam (11384) the patch doesn't work anymore. The error is in the module dvbapi.c , Can you please fix it?
Thankyou!

**Comment by gorgone** [comment]
this is for oscam modern

**Comment by Bigsailor69** [comment]
Thankyou @Gorgone for your answer. This patch is not working. I used instead the patch from your GitHub, and yours is OK.
