### ISSUE TITLE
Constant CW don't recognize other caid, only BISS

### ISSUE THREAD

**Issue by zinonino** [oscam-emu/oscam-emu#239]
When set constantcw in SoftCam.Key oscam-emu don't send request for different caid, exept biss(2600)
Example:

> F 1004100D 00 XXXXXXXXXXXXXXXX
> F 1004100D 01 XXXXXXXXXXXXXXXX
> F 10681071 00 XXXXXXXXXXXXXXXX
> F 10681071 01 XXXXXXXXXXXXXXXX
> F 107C1085 00 XXXXXXXXXXXXXXXX
> F 107C1085 01 XXXXXXXXXXXXXXXX
> F 1072107B 00 XXXXXXXXXXXXXXXX
> F 1072107B 01 XXXXXXXXXXXXXXXX  
> F 1086108F 00 XXXXXXXXXXXXXXXX 
> F 1086108F 01 XXXXXXXXXXXXXXXX

```
[reader]
label = emulator
protocol = emu
device = emulator
caid = 0940,0500,1801,0604,2600,FFFF,0E00,4AE1,1010
detect = cd
ident = 0940:000000;0500:000000,023800,021110,007400,007 800;1801:007301,001101,002111;0604:000000;2600:000000;FFFF:000000;0E00:000000;4AE1:000011,000014,0000FE;1010:000000
group = 1
```

Example are for ConstanCW with CAID 0940

But oscam-emu emulator don't recongnize constantcw with cadi 0940

More about problem discusses here:
http://www.sat-universe.com/showthread.php?t=301803

Use oscam dvbapi with pached emu, not request from CCcam

**Comment by oscam-emu** [comment]
Well, yes, oscam-emu only supports BISS caid with the "F xxxxxxxx xx xxxxxxxxxxxxxxxx" keys.

If you need other caids like those you mention you can use the constant cw reader and a constant.cw file in oscam. That's the proper way to do it anyway.
