### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by cb3hn** [oscam-emu/oscam-emu#241]
CC	module-webif-tpl.c
module-emulator-osemu.c: In function ‘PowervuCalculateCw’:
module-emulator-osemu.c:3463:22: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  uint8_t seedLength, val;
                      ^
CC	webif/pages.c
CC	module-webif.c
CC	reader-common.c
module-emulator-osemu.c: In function ‘PowervuECM’:
module-emulator-osemu.c:3564:10: warning: ‘hashModeCw’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  uint8_t hashModeCw, needsUnmasking, xorMode;
          ^
How can I fix that?
- Patch & Build: 11391
- gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
- GNU Make 3.81

**Comment by oscam-emu** [comment]
This is not a problem actually. You can ignore it. Depending on the compiler might or might not this warning.

Maybe, I'll fix in the future.

**Comment by oscam-emu** [comment]
Fixed with r753
