### ISSUE TITLE
Powervu:A new hash mode [2] is in use.

### ISSUE THREAD

**Issue by richard87112** [oscam-emu/oscam-emu#245]
57°E mtn chanels are black image，A new hash mode [2] is in use

**Comment by eminemkz** [comment]
Has any one has a fix for the hash code 2

**Comment by remytr** [comment]
Yes, ı make softcam.key with new hash modedocuments some satellites

iPhone6s' dan gönderildi

eminemkz <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (2 Kas 2017 06:15):


Has any one has a fix for the hash code 2

**Comment by oscam-emu** [comment]
Fix with r754

**Comment by eminemkz** [comment]
Hi can you send to me the oscam v754

**Comment by eminemkz** [comment]
i am looking for oscam r754 powervu hash code 2 fix

**Comment by eminemkz** [comment]
Hi friend could you have Oscam emu with hash mode 15 in use
