### ISSUE TITLE
Please Add this preparation ..

### ISSUE THREAD

**Issue by fairbird** [oscam-emu/oscam-emu#247]
https://github.com/Hains/oscam/commit/f423419f19c2ec2aa7f2b84cfe455510a5196521

**Comment by oscam-emu** [comment]
This is a pure oscam modification. Nothing to do with the emu.
I believe you should explain to the oscam guys what it does and why this is needed and ask them to commit it in the oscam svn. 

Otherwise, you can tell me what it does and maybe I make a pull request to oscam.

**Comment by fairbird** [comment]
I have add it in my emu build tree and test it ..
Before with some new image as like as ARM boxes emu doesn't work..
And now work just fine ..

Because those image have newest version of openssl..

**Comment by oscam-emu** [comment]
@fairbird as I explained before, these 2 requests are not related to the emu. They are related to oscam. Make a patch and ask the oscam guys to accept it.
