### ISSUE TITLE
pid limiter option cuts some audio streams

### ISSUE THREAD

**Issue by docea37** [oscam-emu/oscam-emu#249]
0.8w thor bbc earth does not sound with the latest patch file. Sounds smoothly with old patch file (patch 755)

**Comment by oscam-emu** [comment]
It should be related to the pid limiter addition. Will investigate.

**Comment by oscam-emu** [comment]
Confirmed. It will be fixed soon.

**Comment by oscam-emu** [comment]
pid limiter is now applied to powervu services only. Default pids is 64 again.
