### ISSUE TITLE
problem with emu dvbapi

### ISSUE THREAD

**Issue by egydoctor2010** [oscam-emu/oscam-emu#256]
what is this error and how to solve it

2018/01/19 14:38:20 7C3BAEB7 c (reader) emulator [emu] EMM: reader_caid 0000 != emmpid caid 5604 -> SKIP!
2018/01/19 14:38:20 7C3BAEB7 c (reader) emulator [emu] EMM: reader 0E00 match since emmpid has no provid -> SEND!
2018/01/19 14:38:28 7C3BAEB7 c (ecm) One (0E00@000000/0000/006C/91:2C7487ED85DEC70C4AD2489F6CE0B106): rejected group (5 ms) - AFN (no matching reader)
2018/01/19 14:38:37 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 27 (errno=75 Value too large for defined data type)
2018/01/19 14:38:37 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 28 (errno=75 Value too large for defined data type)
2018/01/19 14:38:37 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 29 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (ecm) One (0E00@000000/0000/006C/91:F44BDE78FBEDAAFE89C034F4D3786CF6): rejected group (29 ms) - AFN (no matching reader)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 18 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 19 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 20 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 21 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 22 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 23 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 24 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 25 (errno=75 Value too large for defined data type)
2018/01/19 14:38:38 7C3BAEB7 c (dvbapi) ERROR: Read error on fd 26 (errno=75 Value too large for defined data type)

**Comment by oscam-emu** [comment]
I can't understand what the problem is from this log. Make sure you have setup your AFN reader properly.
