### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by arys123** [oscam-emu/oscam-emu#257]
Hi,

if i compile oscam with emu a warning is displayed, but however the emu work. Have anyone the same problem? What is the issues in this funktion PowervuCreateHash?

[ 20%] Building C object CMakeFiles/csmodules.dir/module-camd35.obj
[ 21%] Building C object CMakeFiles/csmodules.dir/module-dvbapi-chancache.obj
[ 22%] Building C object CMakeFiles/csmodules.dir/module-dvbapi-azbox.obj
[ 22%] Building C object CMakeFiles/csmodules.dir/module-emulator-stream.obj
[ 23%] Building C object CMakeFiles/csmodules.dir/module-emulator-osemu.obj
/home/xxxx/oscam-svn/module-emulator-osemu.c: In function `PowervuCreateHash':
/home/xxxx/oscam-svn/module-emulator-osemu.c:3421: warning: 'f' might be used uninitialized in this function
/home/xxxx/oscam-svn/module-emulator-osemu.c:3422: warning: 'f2' might be used uninitialized in this function
/home/xxxx/oscam-svn/module-emulator-osemu.c:3366: warning: 'f' might be used uninitialized in this function
/home/xxxx/oscam-svn/module-emulator-osemu.c:3283: warning: 'f' might be used uninitialized in this function
[ 24%] Building C object CMakeFiles/csmodules.dir/module-monitor.obj
[ 24%] Building C object CMakeFiles/csmodules.dir/module-newcamd.obj
[ 25%] Building C object CMakeFiles/csmodules.dir/module-webif.obj
[ 26%] Building C object CMakeFiles/csmodules.dir/module-newcamd-des.obj

best regards 
arys123

**Comment by oscam-emu** [comment]
Fixed in [r767](https://github.com/oscam-emu/oscam-emu/commit/75f34915ef04d3b8f1b8f93b04db099236229bc8).
