### ISSUE TITLE
New hashmode 7

### ISSUE THREAD

**Issue by ermanske** [oscam-emu/oscam-emu#259]
Sattelite 65w and 75w changed hashmode to hash mode 7. Please if possible compile oscam to it._

Log:

**2018/02/15 13:06:58 0839F904 c      (ecm) root (0E00@000000/0000/008A/48:493A2F016CF4CB379E03D0B5EB47C330): found (6 ms) by emulator - Universal HD
2018/02/15 13:06:59 7BBECD22 r      (emu) A new hash mode [7] is in use.
2018/02/15 13:06:59 0839F904 c        (-) -- Skipped 7 duplicated log lines --
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR_MODE): Operation not permitted
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR): Operation not permitted
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR_MODE): Operation not permitted
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR): Operation not permitted
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR_MODE): Operation not permitted
2018/02/15 13:06:59 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR): Operation not permitted
2018/02/15 13:06:59 0839F904 c      (ecm) root (0E00@000000/0000/008A/48:64204CAE5868F44AD6E938F574C65347): found (4 ms) by emulator - Universal HD
2018/02/15 13:07:00 7BBECD22 r      (emu) A new hash mode [7] is in use.
2018/02/15 13:07:00 0839F904 c        (-) -- Skipped 7 duplicated log lines --
2018/02/15 13:07:00 0839F904 c   (dvbapi) ERROR: ioctl(CA_SET_DESCR_MODE): Operation not permitte**

Regards.

**Comment by oscam-emu** [comment]
Added in [r767](https://github.com/oscam-emu/oscam-emu/commit/75f34915ef04d3b8f1b8f93b04db099236229bc8).
