### ISSUE TITLE
hash mode 10- Intelsat 34 -55w -4015 H 30000 problem -help 

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-emu#263]
ECM[Video]: 
ECM: 80 30 45 50 3F 20 0E 00 D5 08 CE DF 8F B2 CC E6 56 79 00 D2 B0 00 AC 8F F0 EF 84 E1 66 C1 65 C0 F3 62 DB E0 59 14 A0 00 00 1F C5 16 D4 CB 61 B8 DC 88 25 0F 45 1A 12 D5 30 24 AB 5F F2 17 82 96 40 3A 9E C8 A9 05 9E D6
Unmasked ECM: 80 30 45 30 3F 20 0E 00 00 08 CE DF 8F B2 CC E6 56 79 00 D2 B0 00 AC 8F F0 EF 32 4B 66 C1 65 C0 F3 62 DB 82 00 14 A0 00 00 1F 2B B5 55 55 61 B8 2E 88 BF E5 2D 1A 12 D5 30 24 CD 5F 4E 2E 82 96 40 0F 2B C8 98 AA CF DB
IsDecrypted: True
DVB Scrambling Algo: DES
Needs Unmasking: True
ECM Counter: $D2
Nanos: [5]->($20, $3E) 
Nano $20 Extra Data Length: 8
Hash Mode CW: 10, ECM: 10
Seed CW ECM: EF 66 AC C0 8F F3 F0 C1 DB 65 62 00 00 00 00 00 
ECM CalculateSeed: 80 30 45 30 3F 20 0E 00 00 08 CE DF 8F B2 CC E6 56 79 00 D2 B0 00 1C BC 81 95 A0 B0 7D FF 9E E0 27 C2 F0 7D 00 14 A0 00 00 2A 00 83 AC 60 01 01 D6 FE 42 5B 21 01 01 A0 81 F0 00 00 00 C6 00 80 00 DE 14 A0 98 AA CF DB 
Base Cw: 7D FF 9E E0 27 C2 F0 
Seed VPid: 50 AC A2 96 A5 A4 00 00 
Seed APid-1: 90 81 A7 2F CB D7 00 00 
Seed APid-2: 90 81 A7 2F CB D7 00 00 
Seed APid-3: CD 8F 95 D7 75 F5 00 00 
Seed APid-4: CD 8F 95 D7 75 F5 00 00 
Seed HSD: 51 DD 51 FD 7F 66 00 00 
S-Box Type: Primary Tables
Xor Mode: Normal mode[0]
Ident: $14A0
KeyIdx: 1
Key: 63 07 FB 08 48 F1 53 
OddCwAudio1: F7 51 89 9E 6D E5 2A BA 
EvenCwAudio1: 6B 16 32 49 37 E3 3D D9 
OddCwAudio2: F7 51 89 9E 6D E5 2A BA 
EvenCwAudio2: 6B 16 32 49 37 E3 3D D9 
OddCwAudio3: DA 51 7A F1 6D E5 2A BA 
EvenCwAudio3: 37 16 3D 7A 37 E3 3D D9 
OddCwAudio4: DA 51 7A F1 6D E5 2A BA 
EvenCwAudio4: 37 16 3D 7A 37 E3 3D D9 
OddCwVideo: D5 C2 F7 46 EF 5E 13 25 
EvenCwVideo: D6 97 7F A2 54 5B EA 19 
OddCwHSD: E5 C2 43 7A D5 5E 13 25 
EvenCwHSD: D6 97 0E 52 3E 5B EA 19 

TS Before CSA: 
47 0C 3A DE 61 BF AE D7 4A E5 9A 5E 89 75 81 25 BB 67 48 66 94 0C AF 97 30 39 F1 EE 6F 2C F6 A4 2E D4 0F B9 34 62 30 B8 D9 0F D0 04 99 A6 7B AE 20 F0 D2 A3 F2 61 28 97 F2 29 EE 8E B1 2A 74 27 7D 02 A1 E1 7E B4 A5 B9 A8 C7 D3 63 FD 7B 25 89 BA AF 0C 9E B2 BD 48 A9 E2 66 E2 7B EE D5 E5 8F E0 71 46 C4 83 B6 43 26 1E 0A E8 01 47 37 82 06 E3 AF E6 9A 96 48 4E 53 DB F8 33 AA 24 61 1E 44 5B 53 9F 29 AD 7E F6 7E 4B A5 F5 6D C8 D6 DF 40 0A 56 4D 96 C0 9F 0F 68 D2 AA 5B 39 4F C7 4E 16 79 7E DA D3 A7 9C E1 E2 88 E7 79 20 D6 28 C3 DD E1 D0 2D 87 FE 8D F0 AE 48 14 EE 74 

TS After CSA: 
47 0C 3A 1E A0 7D 3D 63 41 C4 6D 9E DD D2 36 C5 67 2F 50 72 3B FA 95 E3 47 52 99 AE 3E 7A 7E 9D 8D 19 18 9E 57 30 66 8A F7 EC A2 9B DE 38 89 E3 7C 6E 04 D2 0A 8B D3 B2 82 14 95 D3 26 20 98 1B B2 11 B4 2E 58 29 27 D1 7C 23 CC 3B 0D F3 5C 64 83 2E 2B 5E 07 CE F3 6A E2 33 73 C8 39 3D 5D 74 B4 EA 1E 2C 76 E4 CB 04 43 DB 6D 3C E7 66 63 19 6A 7E 92 76 69 DA 30 69 DB F6 30 D4 88 29 67 E5 7F B5 6C 77 06 4A CA CA A4 F1 6D CB 48 18 51 03 77 2F 43 E8 B5 72 12 FF DC EA 4A FF 14 D6 35 4B 18 6E D9 36 ED 24 7B AE D5 AA 17 34 12 AC F6 25 23 C3 AB A5 12 B9 27 90 2C 2B 92 80

**Comment by oscam-emu** [comment]
Fixed in https://github.com/oscam-emu/oscam-emu/commit/2380ba68c25bf7782dab7f5115ccdb0dfda359b1
