### ISSUE TITLE
PowerVu mux 4015H30000 SAT 55,5W.

### ISSUE THREAD

**Issue by scolanzi** [oscam-emu/oscam-emu#265]
I'm having problems on the mux Fox from the 55.5W satellite in Powervu. The channels are operating with hash mode EMM = 1 and ECM = 10. The ECM's are correct and in the webif it is showing the normal emulation but it has neither audio nor video. What would be the problem?

**Comment by iptvfta** [comment]
sometime show ECM:9 , hash mode EMM = 1

**Comment by oscam-emu** [comment]
It will be fixed when it's fixed...

**Comment by scolanzi** [comment]
Now the problem has spread to 65W and 75W satellites.
