### ISSUE TITLE
PowerVu 4180V30000 SAT105

### ISSUE THREAD

**Issue by intersect23** [oscam-emu/oscam-emu#266]
since last night i have problems with 105e powervu.
it shows 
(ecm) cam2 (0E00@000000/0000/0047/7E:36EB9A6DA0A35FF8ECF2D425FF42994E): cache1 (0 ms) by OSEmu
but no one channel can not be open

**Comment by oscam-emu** [comment]
Stop asking for a fix. If it doesn't work. then it doesn't...
