### ISSUE TITLE
patch need to fix cw:10

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-emu#272]
Added extra ECM bytes handling with 2 new modes: mode cw and mode unmask. Only modeCw/Unmask = 0 & 3 are implemented

powervu emu test v3,0 emu 

pls fix it

**Comment by oscam-emu** [comment]
Fixed with r770 https://github.com/oscam-emu/oscam-emu/commit/c90f68685b521ddeb84bce35f84d255840c1e48c

**Comment by marrak** [comment]
Thank you for fix.
Could you move debug data 
```
ecm1: [...]
csaUsed [...]
```
from level 0?
