### ISSUE TITLE
oscam-gx (gxapi/csky)

### ISSUE THREAD

**Issue by frankviana** [oscam-emu/oscam-emu#274]
How to compile oscam for csky/gxapi devices? Not found the list (toolchain) using ubuntu.

See the log.

    2018/07/03 13:54:51 00000000 s     (main) System name    = Linux
    2018/07/03 13:54:51 00000000 s     (main) Host name      = gx6602
    2018/07/03 13:54:51 00000000 s     (main) Release        = 2.6.27.55
    2018/07/03 13:54:51 00000000 s     (main) Version        = #36 Mon Apr 23 11:37:32 HKT 2018
    2018/07/03 13:54:51 00000000 s     (main) Machine        = csky
    2018/07/03 13:54:51 00000000 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 9833
    2018/07/03 13:54:51 00000000 s      (emu) OSCam-Emu version 770
    2018/07/03 13:54:51 00000000 s   (config) userdb reloaded: 1 accounts loaded, 0 expired, 0 disabled
    2018/07/03 13:54:51 00000000 s     (main) signal handling initialized
    2018/07/03 13:54:51 00000000 s      (net) cccam: initialized (fd=6, port=20000)
    2018/07/03 13:54:51 5743C305 h    (webif) webif: decompressed 178899 bytes back into 441784 bytes
    2018/07/03 13:54:51 5743C305 h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
    2018/07/03 13:54:51 00000000 s   (reader) emulator [emu] creating thread for device emulator
    2018/07/03 13:54:51 71D9E8C4 r   (reader) emulator [emu] Reader initialized (device=emulator, detect=cd, mhz=357, cardmhz=357)
    2018/07/03 13:54:51 00000000 s   (reader) smartcard [internal] creating thread for device /dev/sc0
    2018/07/03 13:54:51 0427F1CA r   (reader) smartcard [internal] Reader initialized (device=/dev/sc0, detect=cd, mhz=357, cardmhz=357)
    2018/07/03 13:54:51 0427F1CA r   (reader) smartcard [internal] Reader sci internal, detected box type: generic
    2018/07/03 13:54:51 00000000 s     (stat) loadbalancer: could not open /tmp/.oscam/stat for reading (errno=2 No such file or directory)
    2018/07/03 13:54:51 00000000 s     (main) waiting for local card init
    2018/07/03 13:54:52 71D9E8C4 r   (reader) emulator [emu] card detected
    2018/07/03 13:54:53 71D9E8C4 r   (reader) emulator [emu] found card system emu
    2018/07/03 13:54:53 71D9E8C4 r   (reader) emulator [emu] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max alloted of 1
    2018/07/03 13:54:53 71D9E8C4 r      (emu) Reading key file: /home/gx/local/oscam/SoftCam.Key
    2018/07/03 13:54:53 71D9E8C4 r      (emu) WARNING: Wrong key format in SoftCam.Key: F 00010020 0
    2018/07/03 13:54:53 71D9E8C4 r        (-) -- Skipped 1 duplicated log lines --
    2018/07/03 13:54:53 71D9E8C4 r      (emu) Total keys in memory: W:0 V:0 N:0 I:0 S:0 F:52 P:1282 D:0 T:50
    2018/07/03 13:54:54 00000000 s     (main) init for all local cards done
    2018/07/03 13:54:54 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
    2018/07/03 13:54:54 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
    2018/07/03 13:54:54 00000000 s (anticasc) anti cascading disabled
    2018/07/03 13:54:54 3AA2EB9E c   (client) plain dvbapi-client granted (octagon-sx88, au=auto (2 reader))
    2018/07/03 13:54:54 3AA2EB9E c   (dvbapi) dvbapi channelcache loaded from /home/gx/local/oscam/oscam.ccache
    2018/07/03 13:54:54 3AA2EB9E c (dvbgxapi) gxdvbapi_init;119 
    2018/07/03 13:54:54 3AA2EB9E c (dvbgxapi) fun = DEMUX_SoftTSCreate, line  = 890 DemuxName = 0,PTIhandle = 14
    2018/07/03 13:54:54 3AA2EB9E c (dvbgxapi) fun = DEMUX_SoftTSCreate, line  = 890 DemuxName = 1,PTIhandle = 15
    2018/07/03 13:54:55 3AA2EB9E c (dvbgxapi) fun = DEMUX_SoftTSCreate, line  = 890 DemuxName = 2,PTIhandle = 16
    2018/07/03 13:54:56 3AA2EB9E c (dvbgxapi) fun = DEMUX_SoftTSCreate, line  = 890 DemuxName = 3,PTIhandle = 17
    2018/07/03 13:54:56 3AA2EB9E c (dvbgxapi) gxapi init success !!!
    2018/07/03 13:54:56 3AA2EB9E c   (dvbapi) Detected /dev/gxav0 Api: 4, userconfig boxtype: 1 maximum amount of possible filters is 32 (oscam limit is 32)

**Comment by oscam-emu** [comment]
I don't know. It's not really an issue and it's not related to the Emu. Ask the OSCam guys.
