### ISSUE TITLE
Oscam Patch Needed for Hash Mode 15

### ISSUE THREAD

**Issue by facebooknotification777** [oscam-emu/oscam-emu#277]
Hello 

I am new to these stuff but using Enigma2 for a while, Recently some channels on 105.5 E change power VU hash mode to 15 which stop the channels to work.

Is there any body who can patch the oscam for that

Thanks

**Comment by PAKO34** [comment]
AFN HASHMODE 15 
FIX NEED OSCAM PATCH

**Comment by dulcet** [comment]
csaUsed=1, xorMode=0, ecmSrvid=71, hashModeCw=16, modeCW=0 

again hashModeCw change in sony package 105* and 68*

**Comment by oscam-emu** [comment]
Fixed with r772 https://github.com/oscam-emu/oscam-emu/commit/9e07fbc848895c9c62af24137c9c0771294aec52
