### ISSUE TITLE
Patch fails on new 11429 changes...

### ISSUE THREAD

**Issue by joeusercz** [oscam-emu/oscam-emu#279]
Some patches don't apply at all, but worse, at least one patches incorrectly. 
oscam.c patch gets put in wrong place and causes emu reader not to be started.

Here is a quick fix - but not really tested. (builds and seems to work, but I am looking at another issue so don't have time to really test...)

[oscam-emu.patch.11429.770b.zip](https://github.com/oscam-emu/oscam-emu/files/2238903/oscam-emu.patch.11429.770b.zip)

**Comment by oscam-emu** [comment]
Thanks for the info. I fixed it in the [main repo](https://github.com/oscam-emu/oscam-patched), and here as well.
