### ISSUE TITLE
A new hash mode [18] is in use.

### ISSUE THREAD

**Issue by engineerkhan15** [oscam-emu/oscam-emu#287]
Hi, developers. 
Sony Network at Asiasat 7 (105.5 East) is using hash mode 18 for its PowerVu encryption. Can you add a fix for this hash mode in the patch, please?

**Comment by oscam-emu** [comment]
added with r773 https://github.com/oscam-emu/oscam-emu/commit/47c4bd465b447862a83f380294f89455fbccc540
